In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [2]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
]

In [3]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus).T

In [4]:
print(vectorizer.get_feature_names())
print(X.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0]
 [1 2 0 1 1 2 0 1 1 2 0 1 1 2 0 1]
 [1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [5]:
X2 = X.toarray()
X2.shape

(9, 16)

In [6]:
A,B,C=np.linalg.svd(X2,full_matrices=False)

In [7]:
A.shape

(9, 9)

In [8]:
B.shape

(9,)

In [10]:
C.shape

(9, 16)

In [11]:
B

array([8.55921243e+00, 3.96887307e+00, 2.64346913e+00, 7.34952140e-16,
       1.04944231e-16, 1.96624721e-32, 1.87867899e-33, 2.28026840e-49,
       3.77473432e-51])

In [12]:
idx = np.argsort(B)[::-1]
W2 = A[:,idx[:3]]

In [13]:
W2.shape

(9, 3)

In [14]:
W2[0,:]

array([-0.09054904,  0.45229121, -0.15915015])

In [15]:
W2[1,:]

array([-0.51079491, -0.52144343, -0.29365443])